version: '3.8'
########################################
#NOTE - psql############################
########################################
services:
  postgres:
    image: postgres:16
    container_name: whalewkss_pg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: whalewks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - need-erp-tunnel
########################################
#NOTE - pgAdmin#########################
########################################
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} | sarawut.khan@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} | admin
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT} | 5050
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_LISTEN_PORT}:5050"
    restart: always
    networks:
      - need-erp-tunnel
  volumes:
    postgres_data:
    pgadmin_data:
########################################
#NOTE - Go-Backend######################
########################################
  app:
    image: go-fiber:test #เปลี่ยนเป็น images ล่าสุดของตัวเองนา
    container_name: go-fiber-container
    volumes:
      - ./pdf-files:/app/pdf-files
    ports:
      - "8080:8080"
    environment:
      DB_URI: postgresql://admin:admin@postgres:5432/whalewkss
      SECRET_KEYS: secretkeys
      PDF_DIR: /app/pdf-files/
    networks:
      - need-erp-tunnel

networks:
  need-erp-tunnel:
    external: true
